# Source: cluster-api-aws/templates/machine-pool.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: c3dc7h8xh-mp-taco
  namespace: c3dc7h8xh
spec:
  clusterName: c3dc7h8xh
  replicas: 3
  template:
    metadata:
      labels:
            servicemesh: enabled
            taco-ingress-gateway: enabled
            taco-lma: enabled
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: c3dc7h8xh
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: c3dc7h8xh-mp-taco
        namespace: c3dc7h8xh
      version: v1.22.5

